spring.application.name=
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Jackson configuration to handle Hibernate proxies
spring.jackson.serialization.fail-on-empty-beans=false

# JWT Configuration
jwt.secret=
jwt.expiration=

# Spring Security Debug
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.web.access=DEBUG
logging.level.org.springframework.security.access=DEBUG
logging.level.org.springframework.security.method=DEBUG
